---
title: "AMS Blanks"
author: "Brett Longworth"
date: "Jan 17, 2018"
output:
  pdf_document: default
  html_document: default
---

Summary of AMS blanks (Alpha Aesar, Ceylon, acetanalide, and C1) for both machines. Data are from snics_results. I'm rejecting data Fm > 0.02. 


```{r, echo=FALSE, message=FALSE, warning=FALSE}
### load libraries
library(amstools)
library(RODBC)
library(dplyr)
library(ggplot2)
library(shiny)

### Get blank data from DB
from <- "2017-11-01"
to <- "2018-01-15"

# Open DB connection
db <- conNOSAMS()

# Get raw blank data
raw <- sqlQuery(db, paste("
      SELECT runtime, target.tp_date_pressed, target.rec_num, 
          sample_name, target.tp_num, gf_co2_qty, 
          he12c, he13c, d13c, he14_12, he13_12, wheel, ok_calc
        FROM snics_raw, target, graphite
      	WHERE target.tp_num = snics_raw.tp_num
        AND target.osg_num = graphite.osg_num
        AND tp_date_pressed > '", from, "'
        AND tp_date_pressed < '", to, "'
        AND target.rec_num IN (83028, 53804, 2138, 140548, 36168, 55101, 1081, 39246)
        "))

jmer <- sqlQuery(db, paste("
      SELECT runtime, target.tp_date_pressed, target.rec_num, 
          sample_name, target.tp_num, he12c, he13c, d13c, he14_12, 
          he13_12, wheel, ok_calc
        FROM snics_raw, target
      	WHERE target.tp_num = snics_raw.tp_num
        AND tp_date_pressed > '", from, "'
        AND tp_date_pressed < '", to, "'
        AND target.rec_num IN (32490, 32491, 32492, 36947, 148820)
        "))

# add type columns, combine data frames
jmer$gf_co2_qty <- NA
blanks.r <- rbind(raw, jmer)

# average by target and filter
blanks.a <- blanks.r %>%
  group_by(tp_num) %>%
  summarize(
    he12c = mean(ifelse(ok_calc == 1, he12c, NA), na.rm = TRUE),
    he1412 = mean(ifelse(ok_calc == 1, he14_12, NA), na.rm = TRUE),
    flagged = ((n() - sum(ok_calc == 1)) / n()) # fraction of runs flagged
  ) %>%
  mutate(c1412x = he1412 * 1e16)

###
# Get normalized blank data
###

blanks.n <- sqlQuery(db, paste("
      SELECT runtime, wheel, target.tp_date_pressed, sample_name,
          target.rec_num, target.tp_num, gf_co2_qty, 
          norm_ratio, int_err, ext_err, 
          blk_corr_method, fm_corr, sig_fm_corr, ss
        FROM snics_results, target, graphite
        WHERE target.tp_num = snics_results.tp_num
        AND target.osg_num = graphite.osg_num
        AND tp_date_pressed > '", from, "'
        AND tp_date_pressed < '", to, "'
        AND target.rec_num IN (83028, 53804, 2138, 140548, 36168, 55101, 1081, 39246)
        "))


jme <- sqlQuery(db, paste("
       SELECT runtime, wheel, target.tp_date_pressed, sample_name, 
           target.rec_num, target.tp_num,
           norm_ratio, int_err, ext_err,
           blk_corr_method, fm_corr, sig_fm_corr, ss
         FROM snics_results, target
         WHERE target.tp_num = snics_results.tp_num
         AND target.rec_num IN (32490, 32491, 32492, 36947, 148820)
         AND tp_date_pressed > '", from, "'
        AND tp_date_pressed < '", to, "'
         "))

# Close DB
odbcClose(db)

jme$gf_co2_qty <- NA
blanks.n <- rbind(blanks.n, jme)


# combine data
blanks <- left_join(blanks.a, blanks.n, by = "tp_num") %>%
  filter(
    norm_ratio < 0.02,
    norm_ratio > 0
  ) %>%
  mutate(
    tp_date_pressed = as.Date(tp_date_pressed),
    type = ordered(
      recode(
        as.character(rec_num),
        "1081" = "C1",
        "2138" = "TIRI-F",
        "32490" = "JME",
        "32491" = "JME",
        "32492" = "JME",
        "36168" = "Acet",
        "39246" = "C1",
        "53804" = "C1",
        "55101" = "Acet",
        "83028" = "C1",
        "140548" = "Acet",
        "36947" = "Old Ceylon",
        "148820" = "Ceylon"
      ),
      levels = c("Acet", "C1", "TIRI-F", "JME", "Old Ceylon", "Ceylon")
    ),
    merr = pmax(int_err, ext_err),
    system = toupper(substring(wheel, 1, 5)),
    age = rcage(norm_ratio)
  )
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
tb <- blanks %>%
  group_by(system, type) %>%
  summarize(
    Fmodern = mean(norm_ratio, na.rm = TRUE),
    Fmodern.sd = sd(norm_ratio, na.rm = TRUE),
    RCAge = as.integer(round(mean(age), -3)),
    RCAge.sd = as.integer(round(sd(age), -2)),
    N = n()
  )
knitr::kable(tb, digits = 4)
```

```{r, echo=FALSE}
ggplot(blanks, aes(x = type, y = age)) +
  geom_boxplot() + facet_grid(. ~ system) +
  xlab("Blank type") +
  ylab("Radiocarbon age") +
  ggtitle("Blanks by system") + theme_bw() +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(),
    axis.text.x = element_text(angle = 90)
  )
```
  


