---
title: "AMS Blanks"
author: "Brett Longworth"
date: "May 14, 2015"
output: html_document
---

Summary of AMS blanks (JME and C1) for both machines from Sep 2014 to present. 

## Data getting and munging

```{r warning=FALSE, message=FALSE}
library(RODBC)
library(dplyr)
library(ggplot2)
library(knitr)

source("~/R/dbconfig.R") #DB connection info
#Open DB connection
db <- odbcConnect(database, uid = uid, pwd = pwd)

#Get raw blank data
c1 =  sqlQuery(db, paste("
      SELECT runtime, target.tp_date_pressed, sample_name, target.tp_num, 
          he12c, he13c, d13c, he14_12, he13_12, wheel, ok_calc
        FROM snics_raw, target
      	WHERE target.tp_num = snics_raw.tp_num
        AND tp_date_pressed > '2014-09-01'
        AND target.rec_num = 83028
        "))

acet =  sqlQuery(db, paste("
      SELECT runtime, target.tp_date_pressed, sample_name, target.tp_num, 
          he12c, he13c, d13c, he14_12, he13_12, wheel, ok_calc
        FROM snics_raw, target
      	WHERE target.tp_num = snics_raw.tp_num
        AND sample_name LIKE 'Acet%'
        AND tp_date_pressed > '2014-09-01'"))

jme =  sqlQuery(db, paste("
      SELECT runtime, target.tp_date_pressed, sample_name, target.tp_num, 
          he12c, he13c, d13c, he14_12, he13_12, wheel, ok_calc
        FROM snics_raw, target
      	WHERE target.tp_num = snics_raw.tp_num
        AND sample_name LIKE 'Alfa%'
        AND tp_date_pressed > '2014-09-01'"))

#Close DB
odbcClose(db)

#add type columns, combine data frames
c1$type <- "C1"
acet$type <- "Acet"
jme$type <- "JME"
blanks.r <- rbind(c1, acet, jme)
blanks.r$type <- ordered(blanks.r$type, levels = c("Acet", "C1", "JME"))

#average by target and filter
blanks <- blanks.r %>%
  mutate(system = ifelse(grepl("CFAMS", wheel), "CFAMS", "USAMS")) %>%
  filter(ok_calc == 1) %>%
  group_by(tp_num, tp_date_pressed, system, type) %>%
  summarize(
    he12c = mean(he12c),
    he1412 = mean(he14_12)
  ) %>%
  filter(he1412 < 1e-14) %>%
mutate(c1412x = he1412 * 1e16)

#Export data as CSV
write.csv(blanks, "blanks.csv")
```


## Summary

Data are means by target of accepted (unflagged) points. Points above 1e-14 removed.

### Summary table

```{r}

blanks %>%
  group_by(system, type) %>%
  summarize(he1412 = mean(c1412x),
            he1412.sd = sd(c1412x),
            N = n())
```

### Boxplots by system and sample type for all data.

```{r}
ggplot(blanks, aes(x = system, y = c1412x)) + 
  geom_boxplot() + facet_grid(. ~ type) + 
  xlab("System") + ylab("Average 14/12 ratio") +
  ylab(expression(paste("Raw 14/12 ratio ( X", 10^{-16},")"))) +
  theme_bw() + theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
```

### Variability of blanks over time.

```{r, message=FALSE}
qplot(tp_date_pressed, c1412x, color = system, data = blanks) +
  geom_smooth() + facet_grid(type ~ ., scale = "free") +  theme_bw() + 
  theme(panel.grid.minor=element_blank(), panel.grid.major=element_blank())
```

